<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dynastia.Core\Dynastia.Core.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Career\Dynastia.Mechanics.Career.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Education\Dynastia.Mechanics.Education.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Economy\Dynastia.Mechanics.Economy.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.FamilyRelations\Dynastia.Mechanics.FamilyRelations.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Loans\Dynastia.Mechanics.Loans.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Health\Dynastia.Mechanics.Health.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Historical\Dynastia.Mechanics.Historical.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Mortality\Dynastia.Mechanics.Mortality.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Reproduction\Dynastia.Mechanics.Reproduction.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Relationships\Dynastia.Mechanics.Relationships.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.RareEvents\Dynastia.Mechanics.RareEvents.csproj" />
  </ItemGroup>

</Project>