<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Dynastia.TestSupport" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dynastia.App\Dynastia.App.csproj" />
    <ProjectReference Include="..\..\src\Dynastia.Contracts\Dynastia.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Dynastia.Core\Dynastia.Core.csproj" />
    <ProjectReference Include="..\Dynastia.TestSupport\Dynastia.TestSupport.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Career\Dynastia.Mechanics.Career.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Community\Dynastia.Mechanics.Community.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Crafts\Dynastia.Mechanics.Crafts.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Education\Dynastia.Mechanics.Education.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.FamilyRelations\Dynastia.Mechanics.FamilyRelations.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Family\Dynastia.Mechanics.Family.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Households\Dynastia.Mechanics.Households.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.Loans\Dynastia.Mechanics.Loans.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.StatImprovements\Dynastia.Mechanics.StatImprovements.csproj" />
    <ProjectReference Include="..\..\plugins\Dynastia.Mechanics.TurnActions\Dynastia.Mechanics.TurnActions.csproj" />
  </ItemGroup>
</Project>
