namespace Dynastia.App.ViewModels;

public static class EventEmojiMap
{
    private static readonly IReadOnlyDictionary<string, string>
        EmojiMap =
            new Dictionary<string, string>(
                StringComparer.OrdinalIgnoreCase)
            {
                // Exact Dynasty 4 emojiMap keys.
                ["heal"] = "❤️‍🩹",
                ["recover"] = "🛌",
                ["educationSuccess"] = "🎓",
                ["educationFail"] = "🧱",
                ["therapySuccess"] = "😊",
                ["therapyFail"] = "😒",
                ["drink"] = "🍺",
                ["developsAlcoholism"] = " ",
                ["adult"] = "🧑",
                ["receiveInheritance"] = "💰",
                ["retire"] = "🕊️",
                ["releaseFromPrison"] = "✅",
                ["illness"] = "🤧",
                ["seriousIllness"] = "😣",
                ["death"] = "💀",
                ["quitJob"] = "🚶",
                ["divorce"] = "💔",
                ["seekEmploymentSuccess"] = "✅",
                ["askForMoneySuccess"] = "🙏",
                ["askForMoneyFail"] = "🚫",
                ["askToQuitJobSuccess"] = "✅",
                ["askToQuitJobFail"] = "🚫",
                ["askToRecoverSuccess"] = "✅",
                ["askToRecoverFail"] = "🚫",
                ["crime"] = "⛓️",
                ["fired"] = "💥",
                ["promotion"] = "✨",
                ["spouseInheritance"] = "💍",
                ["partnership"] = "👩‍❤️‍👩",
                ["marriage"] = "💍",
                ["affair"] = "🤫",
                ["birthDefect"] = "🧩",
                ["birth"] = "👶",
                ["remarriage"] = "💍",
                ["estateSettled"] = "🏦",
                ["pendingInheritance"] = "⏳",
                ["claimableInheritance"] = "⏳",
                ["householdInheritance"] = "💸",
                ["lostInheritance"] = "💨",
                ["buyHouse"] = "🏠",
                ["sellHouse"] = "💵",
                ["rentHouse"] = "🏘️",
                ["giveHouse"] = "🎁",
                ["houseInheritance"] = "🏡",
                ["houseTransfer"] = "🏡",
                ["hireNanny"] = "🧑‍🍼",
                ["fireNanny"] = "👋",
                ["default"] = "🔹",

                // Modular Dynastia event IDs -> original visual meaning.
                ["wellbeing.heal"] = "❤️‍🩹",
                ["wellbeing.recover"] = "🛌",
                ["education.success"] = "🎓",
                ["education.failure"] = "🧱",
                ["education.help_learning_success"] = "📚",
                ["education.help_learning_failure"] = "📖",
                ["wellbeing.therapy_success"] = "😊",
                ["wellbeing.therapy_failure"] = "😒",
                ["wellbeing.drink"] = "🍺",
                ["life.adult"] = "🧑",

                ["inheritance.received_at_adulthood"] = "💰",
                ["inheritance.received"] = "💸",
                ["inheritance.pending_minor"] = "⏳",
                ["inheritance.claimable"] = "⏳",
                ["inheritance.unclaimed"] = "💨",
                ["inheritance.estate_settled"] = "🏦",
                ["inheritance.houses"] = "🏡",
                ["inheritance.pending"] = "⏳",
                ["inheritance.pending_houses"] = "🏡",
                ["inheritance.received_at_household"] = "💸",
                ["inheritance.pending_houses_received"] = "🏡",
                ["inheritance.estate_left_dynasty"] = "💨",
                ["household.assets_followed_anchor"] = "🏠",
                ["inheritance.promised_houses_received"] = "🏡",

                ["career.retirement"] = "🕊️",
                ["justice.released"] = "✅",
                ["health.illness"] = "🤧",
                ["health.serious_illness"] = "😣",
                ["health.natural_recovery"] = "❤️‍🩹",
                ["health.second_wind"] = "❤️‍🔥",
                ["economy.careful_management"] = "💰",
                ["relationship.divorce_refused"] = "💍",
                ["life.death"] = "💀",
                ["career.quit"] = "🚶",
                ["relationship.divorce"] = "💔",
                ["relationship.marry_off_failed"] = "💒",
                ["relationship.low_satisfaction_divorce"] = "💔",
                ["relationship.repair_marriage"] = "❤️‍🩹",
                ["relationship.prison_divorce"] = "💔",
                ["career.employment"] = "✅",
                ["career.changed_job"] = "💼",
                ["career.relocated"] = "🧳",
                ["career.family_connections_success"] = "🤝",
                ["career.family_connections_failure"] = "🚫",
                ["family_support.parents_success"] = "🙏",
                ["family_support.parents_failure"] = "🚫",
                ["family_support.house_received"] = "🏠",
                ["family_support.house_refused"] = "🚫",
                ["personality.religious_study_success"] = "🙏",
                ["personality.religious_study_failure"] = "🕯️",

                // Filled missing family-support event emojis.
                ["family_support.child_success"] = "🙏",
                ["family_support.child_failure"] = "🚫",

                ["career.ask_quit_success"] = "✅",
                ["career.ask_quit_failure"] = "🚫",
                ["career.ask_recover_success"] = "✅",
                ["career.ask_recover_failure"] = "🚫",
                ["justice.crime"] = "⛓️",
                ["justice.crime_uncaught"] = "🕵️",
                ["career.fired"] = "💥",
                ["career.promotion"] = "✨",
                ["relationship.partnered"] = "👩‍❤️‍👩",
                ["relationship.married"] = "💍",
                ["relationship.affair"] = "🤫",
                ["birth.condition"] = "🧩",
                ["life.birth"] = "👶",
                ["peripheral.birth"] = "👶",
                ["relationship.remarried"] = "💍",

                ["household.house_bought"] = "🏠",
                ["household.house_sold"] = "💵",
                ["household.house_purchase_failed"] = "🚫",
                ["household.moved"] = "🧳",
                ["household.house_rented"] = "🏘️",
                ["household.house_given"] = "🎁",

                // Filled the other missing action-family event emoji.
                ["household.house_promised"] = "🎁",

                ["household.nanny_hired"] = "🧑‍🍼",
                ["household.family_nanny_started"] = "🧑‍🍼",
                ["household.family_nanny_ended"] = "👋",
                ["household.nanny_service_ended"] = "👋",
                ["household.nanny_fired"] = "👋",

                ["adoption.with_mother"] = "👩‍👧",
                ["adoption.orphaned"] = "🕯️",
                ["adoption.placed"] = "🏠",
                ["adoption.orphanage"] = "🏚️",
                ["adoption.left_orphanage"] = "🧳",

                ["rare.house_fire"] = "🔥",
                ["rare.burglary"] = "🕵️",
                ["rare.storm_flood_damage"] = "🌊",
                ["rare.structural_accident"] = "🧱",
                ["rare.assault"] = "🥊",
                ["rare.mugging"] = "💸",
                ["rare.workplace_accident"] = "⚠️",
                ["rare.traffic_accident"] = "🚗",
                ["rare.lightning_strike"] = "⚡",
                ["rare.serious_fall"] = "🤕",
                ["rare.lottery_win"] = "🎰",
                ["rare.distant_inheritance"] = "💰",
                ["rare.fraud"] = "🎭",
                ["rare.found_property"] = "💎",
                ["rare.wrongful_arrest"] = "⚖️",
                ["rare.suicide"] = "🕯️"
            };

    public static string GetEmoji(
        string eventType)
    {
        return EmojiMap.TryGetValue(
            eventType,
            out var emoji)
                ? emoji
                : EmojiMap["default"];
    }
}
